service: serverless-backup-analysis
provider:
  name: aws
  runtime: python3.11
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::dovetail-backup-archive"
        - "arn:aws:s3:::dovetail-backup-archive/*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  include:
    - requirements.txt
    - backup/**
  exclude:
    - tests/**
    - requirements_test.txt
    - requirements_dev.txt

functions:
  backup-analysis:
    handler: backup.main.handler
    events:
      - http:
          path: /
          method: post
          cors: true
